version: "2"
services: 
  web: 
    image: zwffff/consul
    command: consul agent -server -bootstrap -ui -data-dir=/var/lib/consul-data -bind=172.12.0.3 -client=0.0.0.0 -node=server01
    networks:
      consul_testconsul:
        ipv4_address: 172.12.0.3
    container_name: consulserver
    ports:
      - "8300"
      - "8301"
      - "8301/udp"
      - "8302"
      - "8302/udp"
      - "8500"
      - "8600"
      - "8600/udp"
      - "80"

networks:
  consul_testconsul:
    external: true
