version: "2"
services:
  jenkins: 
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    user: root
    ports:
      - "8082:8080"
      - "50000:50000"
    volumes:
      - /root/kk/jenkins/data:/var/jenkins_home
